function redirect(name) {
    console.log("entrou")
    if(name=="C.O.R.O.A"){
        location.assign("https://github.com/guifreitasds/C.O.R.O.A")
    }
    if(name=="EstudoCurso"){
        location.assign("https://github.com/guifreitasds/EstudoCurso")
    }
    if(name=="EstudoInd"){
        location.assign("https://github.com/guifreitasds/EstudoInd")
    }
    if(name=="EstudoUni"){
        location.assign("https://github.com/guifreitasds/EstudoUni")
    }
    if(name=="guifreitasds"){
        location.assign("https://github.com/guifreitasds/guifreitasds")
    }
    if(name=="html-css"){
        location.assign("https://github.com/guifreitasds/html-css")
    }
}