# -*- coding: utf-8 -*-
"""PeopleList.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wRNsjp5D87E3BbzIIXttOQ5Rk5EaiUU_
"""

# Entrada de Nomes, Idade e Sexo

# Declaração das listas usadas no código
nomes = []
idade = []
genero = []

# começo do loop geral
while True:
  # declaraçao de cada entrada de dados
 names = (input('Insira um nome: '))
 age = (input('Insira uma idade: '))
 gender = (input('Insira o gênero: '))
  # declaraçao de cada append (soma do valor do input como ultimo item da lista indicada)
 nomes.append(names)
 idade.append(age)
 genero.append(gender)
  # opção de escolha para o usuario
 continue1 = (int(input('Insira 1 para colocar outra pessoa e 2 para parar de colocar pessoas: ')))
  # uso de estrutura condicional para caso o usuário escolha a não-continuação
 if(continue1 == 2):
    print(nomes) 
    print(idade)
    print(genero)
    break