# -*- coding: utf-8 -*-
"""PeopleList.py

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1wRNsjp5D87E3BbzIIXttOQ5Rk5EaiUU_
"""

# Entrada de Nomes, Idade e Sexo

nomes = []
idade = []
genero = []

while True:
 names = (input('Insira um nome: '))
 age = (input('Insira uma idade: '))
 gender = (input('Insira o gênero: '))
 nomes.append(names)
 idade.append(age)
 genero.append(gender)
 continue1 = (int(input('Insira 1 para colocar outra pessoa e 2 para parar de colocar pessoas: ')))
 if(continue1 == 2):
    print(nomes) 
    print(idade)
    print(genero)
    break
 elif(continue1 == 1):
    names = (input('Insira um nome: '))
    age = (input('Insira uma idade: '))
    gender = (input('Insira o gênero: '))
    nomes.append(names)
    idade.append(age)
    genero.append(gender)
    continue2 = (int(input('Insira 1 para colocar outro nome e 2 para parar de colocar nomes: ')))
 if(continue2 == 2):
   print(nomes)
   print(idade) 
   print(genero)
   break
 elif(continue2 == 1):
    names = (input('Insira um nome: '))
    age = (input('Insira uma idade: '))
    gender = (input('Insira o gênero: '))
    nomes.append(names)
    idade.append(age)
    genero.append(gender)
    continue2 = (int(input('Insira 1 para colocar outro nome e 2 para parar de colocar nomes: ')))
 if(continue2 == 2):
   print(nomes) 
   print(idade) 
   print(genero)
   break