# -*- coding: utf-8 -*-
"""TriangleVerifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KpF79ujuT3R8rCjSBa4qlfMt93gXWXu8
"""

# Programa de Verificação de tipos de triângulos com funções

side1 = int(input("Escreva o primeiro lado: "))
side2 = int(input("Escreva o segundo lado: "))
side3 = int(input("Escreva o terceiro lado: "))

def triangleVerifier():
  if(side1 > side2 + side3) or (side2 > side1 + side3) or (side3 > side1 + side2):
    print("It's not a triangle!")
  else:
    print("It's a triangle")

def typeVerifier():
  if(side1 == side2) and (side2 == side3):
    print("Besides that, it's equilateral")
  elif(side1 == side2) or (side2 == side3) or (side1 == side3):
    print("Besides that, it's isosceles")
  else:
    print("Besides that, it's scalene")


triangleVerifier()
typeVerifier()