# -*- coding: utf-8 -*-
"""AgesVerifier.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yXLFzBCehSGlq80XbP9UKtJUbBQyRvHf
"""

# Pesquisa do IBGE 

ages = []
minors = 0
amount = 1
while True:
 age = (int(input("Escreva a Idade do Entrevistado: ")))
 ages.append(age)
 continue1 = (int(input("Escreva 1 para adicionar mais uma idade ou 2 para parar: ")))
 if(continue1 == 2):
  break
 if(age < 18):
   minors = minors + 1
 if(continue1 == 1):
   amount = amount + 1

print("A maior idade é: " + str(max(ages)) + " anos")

print("A menor idade é: " + str(min(ages)) + " anos")


length = len(ages)

sumAges = sum(ages)

percent = (minors / length) * 100

AgesAverage = sumAges / amount

print("O total de entrevistados foram: " + amount)

print("O total de menores de idade é: " + str(percent) + "%")

print("A média das idades é: " + str(AgesAverage) + " anos")